### ISSUE TITLE
Vertical spacing on checkbox label is off

### ISSUE THREAD

**Issue by thallada** [GoogleChromeLabs/dark-mode-toggle#22]
Thanks for making this handy tool. It's really easy to just plug in and get working.

The icon needs a bit of bottom margin so that it is horizontally aligned with the label text:

![spacing](https://user-images.githubusercontent.com/1505923/71788368-839cc500-2fef-11ea-87bc-19cf9ae710e3.PNG)

The `margin` on `label::before` should be something like `0 .5rem .16rem 0`, not `0 .5rem 0 0`.

Alternatively, I think there's a way to put both elements in a flex container and `align-content: center`.

I can't override it myself since it is in a shadow dom.

**Comment by tomayac** [comment]
This is actually perfectly aligned according to the center line of the font. You can see this by removing the `margin` on the icon with DevTools and setting the `text-decoration` to `line-through`. Below is a screenshot from [your site](https://www.hallada.net/) where I did exactly that:

![Screen Shot 2020-01-07 at 09 48 06](https://user-images.githubusercontent.com/145676/71881754-3c1f5180-3133-11ea-8e64-931a99c3faec.png)

If you really, really dislike it the way it is, you can [specify](https://github.com/googlechromelabs/dark-mode-toggle/#style-customization) an icon image that corrects this (i.e., an image that has additional margin at the bottom.

```css
dark-mode-toggle {
  --dark-mode-toggle-dark-icon: url("/dark-icon-with-margin.png");
  --dark-mode-toggle-light-icon: url("/light-icon-with-margin.png");
}
```
