### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by rctneil** [GoogleChromeLabs/dark-mode-toggle#9]
Is there a way to style the toggle version like this: https://www.cssscript.com/realistic-ios-switch-pure-css/

Thanks.

**Comment by tomayac** [comment]
Yes.

HTML:

```html
<script type=module src=https://unpkg.com/dark-mode-toggle></script>
<dark-mode-toggle class="apple-switch"></dark-mode-toggle>
```

CSS:

```css
.apple-switch {
  position: relative;
  -webkit-appearance: none;
  outline: none;
  width: 50px;
  height: 30px;
  background-color: #fff;
  border: 1px solid #D9DADC;
  border-radius: 50px;
  box-shadow: inset -20px 0 0 0 #fff;
}

.apple-switch:after {
  content: "";
  position: absolute;
  top: 1px;
  left: 1px;
  background: transparent;
  width: 26px;
  height: 26px;
  border-radius: 50%;
  box-shadow: 2px 4px 6px rgba(0,0,0,0.2);
}

.apple-switch[mode=dark] {
  box-shadow: inset 20px 0 0 0 #4ed164;
  border-color: #4ed164;
}

.apple-switch[mode=dark]:after {
  left: 20px;
  box-shadow: -2px 4px 3px rgba(0,0,0,0.05);
}

.dark {
  background-color: black;
}

dark-mode-toggle {
  --dark-mode-toggle-light-icon: none;
  --dark-mode-toggle-dark-icon: none;
}
```

JS:

```js
const toggle = document.querySelector('dark-mode-toggle');
toggle.addEventListener('colorschemechange', () => {
  document.body.classList.toggle('dark', toggle.mode ==='dark', true);
});
```
